name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  laravel-vue:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      APP_KEY: base64:0000000000000000000000000000000000000000000=
      CACHE_DRIVER: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      LOG_CHANNEL: stack
      LOG_LEVEL: warning

      # Use sqlite for CI to avoid external DB
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

      # Dummy Zoho values for build/test phases
      ZOHO_ACCOUNTS_URL: https://accounts.zoho.eu
      ZOHOINV_BASE_URL: https://inventory.zoho.eu/api/v1
      ZOHO_CLIENT_ID: test
      ZOHO_CLIENT_SECRET: test
      ZOHO_REFRESH_TOKEN: test
      ZOHOINV_ORGANIZATION_ID: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
          extensions: mbstring, zip, intl, pdo_sqlite, tokenizer, xml, ctype, bcmath, pcntl, redis

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare .env and key
        run: |
          cp .env.example .env
          php artisan key:generate --force
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations (sqlite)
        run: php artisan migrate --force

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: PHP Unit (if tests exist)
        run: |
          if ls tests/* 1> /dev/null 2>&1; then
            php artisan test --no-interaction
          else
            echo "No tests found, skipping."
          fi

      - name: Upload built assets (artifact)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: public-build
          path: public/build
          if-no-files-found: ignore
